### PR TITLE
 Update default nodejs version to 10.15.1

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by sharifelgamal** [comment]
This failure is legitimate, the shasum check is failing because the signature is invalid. No a whole lot we can do about that.

**Comment by ofrobots** [comment]
It seems that the release was done by a [new Node.js release team member](5599653C). We will need to add their key to the list of keys we have. /cc @DominicKramer wrote some docs on this a while back that you should have.

**Comment by sharifelgamal** [comment]
got it. the documentation for adding a new key is in this repo, so I should be able to take care of this.

**Comment by DominicKramer** [comment]
@sharifelgamal Let me know if you have any problems.

**Comment by sharifelgamal** [comment]
Ok, everything looks good.

**Comment by DominicKramer** [comment]
Awesome.

**Pull request merged**
