### PR TITLE
Add unit tests for the nodeversion Dockerfile

### PR DESCRIPTION
**Pull request by DominicKramer**
* Added unit tests for the nodeversion Dockerfile
* Updated the tests so that even if an error occurs, the
container made by the test will be stopped.  Previously, if an
exception was thrown, the test container would not be stopped.

### CODE REVIEW

**Comment by nkubala** [comment]
just for my own curiosity, do you care more here that the correct node version is returned to you, or that the server just returned anything at all? (i.e. is this more of a structure test around the version of node in the image, or an integration test in the sense that the app works)

**Comment by kjin** [comment]
@nkubala It seems like the purpose of nodeversion is to verify that the `install_node` script really does install the correct version.

**Comment by nkubala** [comment]
@kjin if that's the case, this test is obsolete; this is already being done through a structure test I added a few weeks ago. https://github.com/GoogleCloudPlatform/nodejs-docker/blob/master/test/test_config.yaml#L19

**Comment by kjin** [comment]
OK, it seems like this change is unnecessary... @DominicKramer thoughts?

**Comment by DominicKramer** [comment]
It looks like the CI is using the structure test to run tests, and so perhaps the `test.js` file itself isn't even needed.  If others agree, I won't land this PR and will remove the `test.js` file  in another PR.

**Comment by nkubala** [comment]
IIRC the reason I left `test.js` in the repo is because it's actually spinning up a little server and making sure it can serve requests, which is an integration test (and outside of the scope of the structure testing framework). that being said, I'm working on an integration testing framework that would cover this case and many others like it, so that will make this file totally unnecessary. I don't have the final say, but my opinion would be to just leave this as is for now, and then once I roll out the integration testing framework, do away with this for good.

**Comment by DominicKramer** [comment]
@nkubala In that case, I will leave the `test.js` file in, but it looks like this nodeversion test isn't needed because it is only testing whether a server serves the version.  Thus it looks like the combination of your testing framework and the express test means that this nodeversion test isn't needed.

I won't land this PR then.  Let me know what you think.  Thanks.

**Comment by nkubala** [comment]
@DominicKramer yeah I think just holding off on this for now is the way to go. unless anyone disagrees I'd say go ahead and close

**Pull request closed without merging**
