### PR TITLE
adding support for TAG environment variable

### PR DESCRIPTION
**Pull request by sharifelgamal**

### CODE REVIEW

**Comment by DominicKramer** [comment]
Is this change aligning the code to work with the way in which the runtime builder will be released?

**Comment by sharifelgamal** [comment]
I'm adding functionality to my auto build and release script that requires the use of specifically the TAG environment variable.

**Comment by DominicKramer** [comment]
LGTM

Should this land before or after a new release of the image is made?

**Comment by sharifelgamal** [comment]
A new release shouldn't interfere with this, I made the change backwards compatible with the older version of the script to make it as non-intrusive as possible.

**Comment by DominicKramer** [comment]
Ok then I'll land my PR and start the release process.

**Pull request merged**
