### PR TITLE
Add imagemagick package to the image

### PR DESCRIPTION
**Pull request by swalkowski**
@JustinBeckwith @ofrobots

### CODE REVIEW

**Comment by ofrobots** [comment]
LGTM. We'll try to get this landed later this week after we've successfully upgraded the default image to `v6.9.0` LTS due out today.

**Comment by JustinBeckwith** [comment]
LGTM

**Comment by abiyasa** [comment]
This is awesome 👍 ! Just some questions: 

- Does this mean imagemagick is only available when we use GAE Flexible Env with custom runtime (`runtime: custom`), or is it also available for nodejs runtime (`runtime: nodejs`)?
- Is it documented what libraries are or will be available on the Node.js runtime?

Thanks again

**Comment by kjin** [comment]
@abiyasa Thanks for your interest! It should work for `runtime: nodejs`, or with `runtime: custom` as long as your custom Dockerfile uses the nodej image as a base (`FROM gcr.io/google_appengine/nodejs`).

Apart from the Dockerfile source itself I believe this is not documented publicly anywhere yet, but we will update the docs.

**Pull request merged**
