### PR TITLE
fix: update release keys for node v16.18.0

### PR DESCRIPTION
**Pull request by ni500**
This PR fix the `gpg: Can't check signature: public key not found` error

### CODE REVIEW

**Review by juanarbol — APPROVED** [review]
Hey! Thanks for the heads up! From my side, I've uploaded my gpg key to pgp.mit.edu server.

Maybe @RafaelGSS should do the same thing. Not that sure

LGTM

**Review by juanarbol — APPROVED** [review]
Hey! Thanks for the heads up! From my side, I've uploaded my gpg key to pgp.mit.edu server.

Maybe @RafaelGSS should do the same thing. Not that sure

LGTM

**Review by RafaelGSS — COMMENTED** [review]
Well... the mine is supposed to be there too.

```
~$ gpg --keyserver hkps://keys.openpgp.org --recv-keys 890C08DB8579162FEE0DF9DB8BEAB4DFCF555EF4
gpg: /home/rafaelgss/.gnupg/trustdb.gpg: trustdb created
gpg: key 8BEAB4DFCF555EF4: public key "RafaelGSS <rafael.nunu@hotmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```

**Comment by RafaelGSS** [comment]
Looks like we aren't using this server for new releasers. Anyway, just uploaded it. It should take some time to propagate (one of the reasons we switched the servers)

**Comment by jahjahbin** [comment]
This may have been fixed by #264 . We should have looked at this PR and at least said _something_. I'm sorry about that.

**Comment by jahjahbin** [comment]
Closing, let us know if there are still issues.

**Pull request closed without merging**
