### PR TITLE
Install NVM and some versions of node.

### PR DESCRIPTION
**Pull request by mindhog**
Install NVM and the three most recent minor versions of Node.

### CODE REVIEW

**Comment by mindhog** [comment]
> Just to double check - this won't get run every time a user builds from this image, right? We only do the > installs when we build?

That's right, this only happens when we're building the base image.

> No need to include 0.odd version releases, they're unstable and not usually used in prod.

Removed 0.11

> Does it default to the latest version if not otherwise specified? Linking what's here to engines in another PR?

I think it did with one of my first incarnations, but the latest version didn't seem to.  Here's where things get ugly: nvm is a shell script that must be sourced.  "nvm use" works by modifying the PATH.  So I think the "right" way to do this from nvm's perspective is to add the "use" to .bashrc and then (for the CMD line) launch npm through the shell.  :-/

I realize this is suboptimal. We could avoid running this under the shell by substituting our own shell script which ends by execing npm.

**Comment by ofrobots** [comment]
What would be pros of providing different versions using `nvm` in the same image vs. using docker tags, like the official images do: https://hub.docker.com/r/library/node/?

**Comment by mindhog** [comment]
Only that maintaining a large number of images has proven problematic.

**Comment by ofrobots** [comment]
IMO, it is going to be more problematic to use nvm for this purpose. nvm is a development tool and not really designed for the production use-case. Any node sub-tasks that are launched without a shell, or as a different user than root, are not going to pick up nvm. Also, in production, I wouldn't want confusion, or the extra footprint by having multiple versions of node in the same docker image.

I'm -2 on this.

**Comment by mindhog** [comment]
> IMO, it is going to be more problematic to use nvm for this purpose. nvm is a development tool and 
> not really designed for the production use-case. Any node sub-tasks that are launched without a 
> shell, or as a different user than root, are not going to pick up nvm. Also, in production, I wouldn't

That would only be a problem for subtasks that invoke node or npm as absolute paths.  PATH is exported, so any subtasks resolving the binary from the path should get the correct version. 

> want confusion, or the extra footprint by having multiple versions of node in the same docker image.

I would love to see us have multiple images for these, but that's not a problem we can solve here.  If we have to install multiple node versions on the same image, do you think we should use nvm, something else, or roll our own solution?

**Comment by JustinBeckwith** [comment]
Are we still looking to do this?  Or can we close this out?

**Comment by mindhog** [comment]
We ended up installing these at image build time, so this is no longer relevant.

**Pull request closed without merging**
