### PR TITLE
Add Node.js release key for Gibson Fahnestock

### PR DESCRIPTION
**Pull request by DominicKramer**

### CODE REVIEW

**Comment by ofrobots** [comment]
I see the new script `docker_gen_keys.sh`, but I can't spot where this gets called. Can you elaborate?

**Comment by DominicKramer** [comment]
The `docker_gen_keys.sh` file is designed to be run manually whenever the keys need to be updated.

**Comment by ofrobots** [comment]
Can we add a document with the process involved with updating the keys file. That will make it easy for the next time.

**Comment by DominicKramer** [comment]
I've documented how to add a new key.

**Pull request merged**
