### PR TITLE
Update nodejs default to 4.2.1

### PR DESCRIPTION
**Pull request by dlorenc**

### CODE REVIEW

**Comment by abiyasa** [comment]
Is v4.2.1 (or v4.2.2) already available at gcr?
I deployed my Node.js app to GAE managed VM yesterday, but when I SSH into the VM, I still got 0.12.7 on `node --version`.

Thanks!

**Comment by JustinBeckwith** [comment]
The change to 4.2.1 should be rolling out this week (right @dlorenc ?).  That change only impacts the default version that's on the image.  Did you try pinning the engines field in your package.json?  This works for me:

```json
"engines": {
  "node": "4.2.2"
}
```

Hope this helps!

**Comment by abiyasa** [comment]
Thanks @JustinBeckwith for the answer. Unfortunately, I have engines field set on my package.json but it still doesn't work. Calling `/nodejs/bin/node --version` inside the container still return 0.12.7

**Comment by JustinBeckwith** [comment]
Ok - a few questions :)  How are you using this image?  Are you deploy to App Engine with `gcloud app deploy`?  Could you paste the console output of your deploy command?

**Comment by abiyasa** [comment]
I use `gcloud preview app deploy app.yaml` to deploy.

Here's the console output from the command (I've replaced the project id :-) ):

```
WARNING: Soon, deployments will set the deployed version to receive all traffic by
default.

To keep the current behavior (where new deployments do not receive any traffic),
use the `--no-promote` flag or run the following command:

  $ gcloud config set app/promote_by_default false

To adopt the new behavior early, use the `--promote` flag or run the following
command:

  $ gcloud config set app/promote_by_default true

Either passing one of the new flags or setting one of these properties will
silence this message.

You are about to deploy the following modules:
 - project-protoman/default (from [/Users/abiyasa/works/protoman/app.yaml])
     Deployed URL: [https://20151110t100000-dot-project-protoman.appspot.com]
     (add --promote if you also want to make this module available from
     [https://project-protoman.appspot.com])

Beginning deployment...
Verifying that Managed VMs are enabled and ready.

Provisioning remote build service.
Copying certificates for secure access. You may be prompted to create an SSH keypair.
Building and pushing image for module [default]
----------------------------- DOCKER BUILD OUTPUT ------------------------------
Step 0 : FROM gcr.io/google_appengine/nodejs
---> 49d1865ecb8d
Step 1 : COPY package.json /app/
---> 340b04382349
Removing intermediate container 48a605056193
Step 2 : RUN npm --unsafe-perm install --production
---> Running in bc8167f43cf4
> bcrypt@0.8.5 install /app/node_modules/bcrypt
> node-gyp rebuild
make: Entering directory `/app/node_modules/bcrypt/build'
CXX(target) Release/obj.target/bcrypt_lib/src/blowfish.o
CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt.o
CXX(target) Release/obj.target/bcrypt_lib/src/bcrypt_node.o
SOLINK_MODULE(target) Release/obj.target/bcrypt_lib.node

... (truncated)


---> 4034a3dc58b9
Removing intermediate container bc8167f43cf4
Step 3 : COPY . /app/
---> b997ef4528be
Removing intermediate container 74614761a1ae
Step 4 : CMD npm start
---> Running in c117003b5e76
---> 10853fca60d2
Removing intermediate container c117003b5e76
Successfully built 10853fca60d2
--------------------------------------------------------------------------------

Copying files to Google Cloud Storage...
Synchronizing files to [gs://staging.project-protoman.appspot.com/].
Updating module [default]...\Deleted [https://www.googleapis.com/compute/v1/projects/project-protoman/zones/us-central1-f/instances/gae-builder-vm-20151110t100000].
Updating module [default]...done.
Deployed module [default] to [https://20151110t100000-dot-project-protoman.appspot.com]

```

**Comment by JustinBeckwith** [comment]
What's your package.json look like?  Also can you run gcloud components update?

**Comment by abiyasa** [comment]
I've run gcloud components update 2 days ago so I got `All components are up to date`.

Here's my package.json:

```
{
  "name": "protoman",
  "version": "0.3.0",
  "description": "protoman application",
  "private": true,
  "main": "index.js",
  "engines" : {
    "node" : "4.2.2"
  },
  "scripts": {
    "test": "grunt test",
    "start": "node index.js",
    "build": "grunt build",
    "lint": "grunt jshint"
  },
  "dependencies": {
    "bcrypt": "^0.8.0",
    "bluebird": "^2.9.25",
    "confit": "^1.2.0",
    "connect-flash": "^0.1.1",
    "dustjs-helpers": "~1.6.3",
    "dustjs-linkedin": "~2.6.2",
    "engine-munger": "^0.2.8",
    "express": "^4.12.3",
    "gcloud": "^0.24.1",
    "kraken-js": "^1.0.5",
    "localizr": "^0.1.6"
  },
  "devDependencies": {
    "browserify": "^5.11.0",
    "browserify-dustjs": "^0.1.1",
    "browserify-shim": "^3.8.0",
    "chai": "^3.2.0",

... (truncated)
    
    "grunt-karma": "^0.12.1"
  },
  "browserify": {
    "transform": [
      "browserify-shim",
      "browserify-dustjs"
    ]
  },
  "browser": {
    "jquery": "./node_modules/jquery/dist/jquery.js",
    "bootstrap": "./node_modules/bootstrap/dist/js/bootstrap.js"
  },
  "browserify-shim": {
    "jquery": "$",
    "bootstrap": {
      "depends": [
        "jquery"
      ]
    }
  }
}
```

**Comment by abiyasa** [comment]
Here's my Dockerfile:

```
FROM gcr.io/google_appengine/nodejs

COPY package.json /app/

RUN npm --unsafe-perm install --production
COPY . /app/
CMD npm start
```

and app.yaml:

```
runtime: custom
vm: true
api_version: 1

# [START scaling]
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 2
  cool_down_period_sec: 60
  cpu_utilization:
    target_utilization: 0.5
# [END scaling]

health_check:
  enable_health_check: True
  check_interval_sec: 10
  timeout_sec: 8
  unhealthy_threshold: 2
  healthy_threshold: 2
  restart_threshold: 60

env_variables:
  NODE_ENV: production

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^(.*/)?.*/node_modules/.*$
- ^(.*/)?.*\.log$
```

**Comment by JustinBeckwith** [comment]
Ah!  That's what was missing.  For better or for worse, the code that auto-installs the right node version is placed into a Dockerfile we generate for you ambiently when you run `gcloud app deploy`.  That only happens if `runtime: nodejs` in your `app.yaml`.    

Do you need to have your own dockerfile?  You could just delete that, use `runtime: nodejs` in your app.yaml, and this should work.  Alternatively, if you need to have your own dockerfile you can run `gcloud preview app gen-config --custom`.  This will generate a dockerfile for you that has all of the runtime choosing code.

**Comment by abiyasa** [comment]
Thanks @JustinBeckwith! I'm not aware that you could generate Dockerfile using gcloud command. I will try this & hopefully it works. Thanks again!

**Comment by abiyasa** [comment]
I just want to confirm that both ways (setting runtime to nodejs or generate dockerfile via gcloud) are working. I got my image build with Node.js v4.2.2. 
Unfortunately, my npm start failed due to binding error on bcrypt (`/app/node_modules/bcrypt/node_modules/bindings/bindings.js:83`) but that's another issue anyway.

Thanks for the help

**Pull request merged**
